site_name: CalcAcoustics 
site_url: https://abc.def
docs_dir: ../docs
theme: readthedocs
nav:
  - Home: index.md
  - Turorial: tutorials.md
  - How-to Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
