site_name: CalcAcoustics 
site_url: https://abc.def
docs_dir: ../docs
theme: readthedocs
nav:
  - Home: index.md
  - Using CalcAcoustics: using_calcacoustics/uc_index.md
  - Creating Calculators: creating_calculators/cc_index.md
  - Developing CalcAcoustics: develop_calcacoustics/dc_index.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
