site_name: CalcAcoustics 
site_url: https://abc.def
docs_dir: ../docs
theme: readthedocs
nav:
  - Home: index.md
  - Turorial: tutorials.md
  - How-to Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
